import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router';
import styles from '../styles/Home.module.css'

export default function Home() {
  const { query } = useRouter();
  console.log(query)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Code <a href="#">Mercado Livre</a>
        </h1>

        <p className={styles.description}>
          {query?.code}
        </p>
 
      </main >

 
    </div >
  )
}
